version: "3"
services:
  db:
    image: postgres
    restart: always
    ports: 
      - 4457:5432
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
  
  node_app:
    container_name: node_app
    build: ./back-end
    ports: 
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env

  app_react:
    container_name: app_react
    build: ./front-end
    volumes:
      - build_react:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - app_react
      - db
      - node_app

volumes:
  db:
  build_react:
